name: Sync submodules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-submodules:
    if: "!contains(github.event.head_commit.message, '[skip-submodule-sync]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest in submodules and commit updates
        run: |
          for submodule in sse mqtt-web; do
            echo "Checking for updates in $submodule..."

            # Save current SHA
            old_sha=$(git rev-parse $submodule)

            cd $submodule
            git checkout main
            git pull origin main
            cd - > /dev/null

            # Save new SHA
            new_sha=$(git rev-parse $submodule)

            if [ "$old_sha" != "$new_sha" ]; then
              echo "Submodule $submodule updated. Committing change."
              git add $submodule
              git commit -m "chore: update $submodule submodule to latest main [skip-submodule-sync]"
            else
              echo "No update in $submodule"
            fi
          done

      - name: Push updates back to main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git fetch origin main
          git rebase origin/main
          git push origin main
